flush ruleset

table ip6 nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oif "eth0" masquerade
	}
}
table ip nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oif "eth0" masquerade
	}
}
