frr defaults datacenter
hostname opnsense-testbed
log syslog informational
!
router bgp 4200000001
 bgp router-id 10.250.250.2
 no bgp default ipv4-unicast
 neighbor MWAN peer-group
 neighbor MWAN remote-as 4200000001
 neighbor MWAN bfd
 neighbor 10.250.250.3 peer-group MWAN
 neighbor 10.250.250.4 peer-group MWAN
 neighbor 3d06:bad:b01:201::3 peer-group MWAN
 neighbor 3d06:bad:b01:201::4 peer-group MWAN
 !
 address-family ipv4 unicast
  neighbor 10.250.250.3 activate
  neighbor 10.250.250.3 route-map PREFER-PRIMARY in
  neighbor 10.250.250.4 activate
  neighbor 10.250.250.4 route-map PREFER-BACKUP in
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 3d06:bad:b01:201::3 activate
  neighbor 3d06:bad:b01:201::3 route-map PREFER-PRIMARY in
  neighbor 3d06:bad:b01:201::4 activate
  neighbor 3d06:bad:b01:201::4 route-map PREFER-BACKUP in
 exit-address-family
exit
!
route-map PREFER-PRIMARY permit 10
 set local-preference 200
exit
!
route-map PREFER-BACKUP permit 10
 set local-preference 100
exit
!
bfd
 peer 10.250.250.3
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 exit
 !
 peer 10.250.250.4
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 exit
 !
 peer 3d06:bad:b01:201::3
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 exit
 !
 peer 3d06:bad:b01:201::4
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 exit
exit
