interface eth0
{
    AdvSendAdvert on;
    MinRtrAdvInterval 30;
    MaxRtrAdvInterval 100;
    AdvManagedFlag on;
    AdvOtherConfigFlag on;
    prefix 3d06:bad:b01:240::/60
    {
        AdvOnLink off;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
};
