#!/usr/bin/env bash
# Generated by Ansible
#
# What it does (symptoms):
# - Re-applies IPv6 NPT rules for all WANs in one shot (boot/deploy safety net).
#
# What it does (technical):
# - Sources `/etc/mwan/mwan.env` for iface names and per-WAN /60 NPT targets.
# - Calls `/usr/local/bin/update-npt.sh <iface> <prefix>` for each configured WAN.
#
# Dependency graph:
# - Called by: `mwan-update-npt.service` (ExecStart).
# - Requires: nftables loaded; interfaces exist (gated by `mwan-wait-npt-prereqs.sh`).

set -euo pipefail

# shellcheck disable=SC1091
. /etc/mwan/mwan.env

TRACE_FILE="${MWAN_TRACE_FILE:-/run/mwan-trace-id}"
MWAN_TRACE_ID="${MWAN_TRACE_ID:-}"
if [ -z "${MWAN_TRACE_ID:-}" ] && [ -r "$TRACE_FILE" ]; then
  MWAN_TRACE_ID="$(cat "$TRACE_FILE")"
fi

log() {
  local prefix=""
  [ -n "${MWAN_TRACE_ID:-}" ] && prefix="traceId=${MWAN_TRACE_ID} "
  logger -t mwan-update-npt-all "${prefix}$*" || true
  echo "[mwan-update-npt-all] ${prefix}$*"
}

run_one() {
  local ifc="$1"
  local cidr="$2"

  [ -n "$ifc" ] || return 0
  [ -n "$cidr" ] || return 0

  log "Updating NPT: iface=$ifc prefix=$cidr"
  /usr/local/bin/update-npt.sh "$ifc" "$cidr"
}

run_one "${MWAN_ATT_VLAN_IFACE:-}" "${MWAN_NPT_ATT_PREFIX:-}"
run_one "${MWAN_WEBPASS_IFACE:-}" "${MWAN_NPT_WEBPASS_PREFIX:-}"
run_one "${MWAN_MONKEYBRAINS_IFACE:-}" "${MWAN_NPT_MONKEYBRAINS_PREFIX:-}"

log "Done"
