#!/usr/bin/env bash
# Generated by Ansible
#
# What it does (symptoms):
# - Prevents boot/deploy races where IPv6 “randomly breaks” because NPT rules were attempted before prerequisites
#   existed (e.g. WAN netdevices not present yet or `nft table ip6 nat` not loaded yet).
#
# What it does (technical):
# - Waits for WAN interfaces to exist in `/sys/class/net/…`.
# - Waits for `nft list table ip6 nat` to succeed (base rules loaded).
# - Exits non-zero on timeout so systemd can retry the parent unit.
#
# Dependency graph:
# - Called by: `mwan-update-npt.service` as `ExecStartPre=...`.
# - Enables: safe execution of `/usr/local/bin/update-npt.sh`.
# - Requires: `nft` and WAN netdevices.

set -euo pipefail

# shellcheck disable=SC1091
. /etc/mwan/mwan.env

ATT_VLAN="${MWAN_ATT_VLAN_IFACE:-}"
WEBPASS_IFACE="${MWAN_WEBPASS_IFACE:-}"
MB_IFACE="${MWAN_MONKEYBRAINS_IFACE:-}"

IFACE_WAIT_SECS="${IFACE_WAIT_SECS:-60}"
NFT_WAIT_SECS="${NFT_WAIT_SECS:-30}"
TRACE_FILE="${MWAN_TRACE_FILE:-/run/mwan-trace-id}"
MWAN_TRACE_ID="${MWAN_TRACE_ID:-}"
if [ -z "${MWAN_TRACE_ID:-}" ] && [ -r "$TRACE_FILE" ]; then
  MWAN_TRACE_ID="$(cat "$TRACE_FILE")"
fi

log() {
  local msg="$1"
  local prefix=""
  [ -n "${MWAN_TRACE_ID:-}" ] && prefix="traceId=${MWAN_TRACE_ID} "
  logger -t mwan-wait-npt-prereqs "${prefix}${msg}"
  echo "[mwan-wait-npt-prereqs] ${prefix}${msg}"
}

wait_for_iface() {
  local iface="$1"
  for _ in $(seq 1 "$IFACE_WAIT_SECS"); do
    [ -d "/sys/class/net/$iface" ] && return 0
    sleep 1
  done
  return 1
}

wait_for_nft_table() {
  for _ in $(seq 1 "$NFT_WAIT_SECS"); do
    nft list table ip6 nat >/dev/null 2>&1 && return 0
    sleep 1
  done
  return 1
}

log "Waiting for WAN interfaces to exist: $ATT_VLAN, $WEBPASS_IFACE, $MB_IFACE (timeout=${IFACE_WAIT_SECS}s)"
wait_for_iface "$ATT_VLAN" || {
  log "WAN interface not present: $ATT_VLAN"
  exit 1
}
wait_for_iface "$WEBPASS_IFACE" || {
  log "WAN interface not present: $WEBPASS_IFACE"
  exit 1
}
wait_for_iface "$MB_IFACE" || {
  log "WAN interface not present: $MB_IFACE"
  exit 1
}

log "Waiting for nftables table to exist: ip6 nat (timeout=${NFT_WAIT_SECS}s)"
wait_for_nft_table || {
  log "nftables table not ready: ip6 nat"
  exit 1
}

log "Prerequisites satisfied"
