#!/usr/bin/env bash
# Generated by Ansible
#
# What it does (symptoms):
# - Gives every boot a stable `traceId` so logs across services/scripts can be correlated end-to-end.
#
# What it does (technical):
# - Generates a boot-scoped ID and writes it to `/run/mwan-trace-id` and `/var/lib/mwan/trace-id`.
# - Logs the traceId to syslog (`logger -t mwan-trace-boot`).
#
# Dependency graph:
# - Runs as: `mwan-trace-boot.service` early in boot.
# - Read by: MWAN scripts/hooks which include `traceId=...` in logs if present.

set -euo pipefail

install -d -m 0755 /run /var/lib/mwan

boot_id="$(cut -c1-8 </proc/sys/kernel/random/boot_id)"
ts="$(date +%Y%m%d-%H%M%S)"
tid="${ts}-boot-${boot_id:-unknown}"

printf '%s\n' "$tid" | tee /run/mwan-trace-id /var/lib/mwan/trace-id >/dev/null
logger -t mwan-trace-boot "traceId=$tid"
