#!/usr/bin/env bash
# Generated by Ansible
#
# Refresh the nftables set `inet mangle att_pinned_v4`:
# - seeds static CIDRs from group_vars
# - resolves configured FQDNs (e.g. Verizon Wi‑Fi Calling) to A records
# - optionally pulls Zoom published IPv4 prefixes from the Zoom JSON feed

set -euo pipefail

# shellcheck disable=SC1091
. /etc/mwan/mwan.env

TABLE="inet"
NFT_TABLE="mangle"
SET_NAME="att_pinned_v4"

DEBUG="${MWAN_DEBUG_LOGGING:-0}"
DEBUG_LOG="${MWAN_DEBUG_LOG:-/var/log/mwan-debug.log}"
TRACE_FILE="${MWAN_TRACE_FILE:-/run/mwan-trace-id}"
MWAN_TRACE_ID="${MWAN_TRACE_ID:-}"
if [ -z "${MWAN_TRACE_ID:-}" ] && [ -r "$TRACE_FILE" ]; then
    MWAN_TRACE_ID="$(cat "$TRACE_FILE")"
fi

log() {
    local prefix=""
    [ -n "${MWAN_TRACE_ID:-}" ] && prefix="traceId=${MWAN_TRACE_ID} "
    logger -t update-att-pinned "${prefix}$*" || true
    echo "[update-att-pinned] ${prefix}$*"
}

debug_json() {
    [ "$DEBUG" = "1" ] || return 0
    local loc="$1"; shift
    local msg="$1"; shift
    local data="${1:-{}}"; shift || true
    jq -cn \
      --arg traceId "${MWAN_TRACE_ID:-}" \
      --arg component "update-att-pinned" \
      --arg location "$loc" \
      --arg message "$msg" \
      --arg data "${data:-{}}" \
      --argjson timestamp "$(date +%s%3N)" \
      '{
        traceId: $traceId,
        component: $component,
        location: $location,
        message: $message,
        data: (try ($data | fromjson) catch {}),
        timestamp: $timestamp
      }' >> "$DEBUG_LOG"
}

ensure_set_exists() {
    nft list set $TABLE $NFT_TABLE $SET_NAME >/dev/null 2>&1
}

set_flush() {
    nft flush set $TABLE $NFT_TABLE $SET_NAME
}

set_add() {
    # Add one element at a time to avoid oversized commands.
    local elem="$1"
    [ -n "$elem" ] || return 0
    nft add element $TABLE $NFT_TABLE $SET_NAME "{ $elem }"
}

resolve_v4() {
    local name="$1"
    # Use getent for portability.
    getent ahostsv4 "$name" 2>/dev/null | awk '{print $1}' | sort -u
}

append_seed_cidrs() {
    local tmp="$1"
    local cidr

    for cidr in ${MWAN_ATT_PINNED_V4_SEED_CIDRS:-}; do
        [ -n "$cidr" ] || continue
        echo "$cidr" >>"$tmp"
    done
}

append_fqdn_a32s() {
    local tmp="$1"
    local fqdn="$2"
    local ip

    while read -r ip; do
        [ -n "$ip" ] || continue
        echo "$ip/32" >>"$tmp"
    done < <(resolve_v4 "$fqdn" || true)
}

append_fqdn_lists() {
    local tmp="$1"
    local fqdn

    for fqdn in ${MWAN_ATT_PINNED_V4_FQDNS:-}; do
        [ -n "$fqdn" ] || continue
        append_fqdn_a32s "$tmp" "$fqdn"
    done
}

zoom_v4_prefixes() {
    local url="${MWAN_ZOOM_IPRANGES_URL:-}"
    [ -n "$url" ] || return 0

    # Prefer parsing Zoom's plain-text prefix lists (one prefix per line), but also support the
    # older JSON format (ip_prefix fields) if you swap the URL back.
    if echo "$url" | grep -qiE '\\.json($|\\?)'; then
        curl -fsSL "$url" 2>/dev/null \
          | jq -r '.. | .ip_prefix? // empty' 2>/dev/null \
          | awk '/^[0-9]+\\./{print}' \
          | sort -u
    else
        curl -fsSL "$url" 2>/dev/null \
          | awk '/^[0-9]+\\./{print}' \
          | sort -u
    fi
}

main() {
    if ! ensure_set_exists; then
        log "nft set missing: $TABLE $NFT_TABLE $SET_NAME"
        exit 1
    fi

    # Build element list in a temp file (one element per line)
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT

    append_seed_cidrs "$tmp"
    append_fqdn_lists "$tmp"

    # Zoom feed (optional)
    while read -r cidr; do
        [ -n "$cidr" ] || continue
        echo "$cidr" >>"$tmp"
    done < <(zoom_v4_prefixes || true)

    # De-dupe and apply
    set_flush

    # Add elements (one-per-line)
    count=0
    while read -r elem; do
        [ -n "$elem" ] || continue
        set_add "$elem"
        count=$((count + 1))
    done < <(sort -u "$tmp")

    [ "$DEBUG" = "1" ] && debug_json "APPLY" "elements_applied" "$(jq -cn --argjson count "$count" '{count: $count}')"

    log "Pinned set updated"
}

main "$@"

