#!/usr/bin/env bash
# Generated by Ansible
#
# MWAN Watchdog: monitors internet connectivity from the Proxmox host and
# automatically rolls back VM 113 to its latest pre-deploy snapshot when a
# recent deploy breaks routing.
#
# Runs on the Proxmox hypervisor (vault), NOT inside the MWAN VM.
# Uses `qm guest exec` over virtio-serial to probe inside the VM when direct
# connectivity from Proxmox is down.
#
# Connectivity test path (mirrors real client traffic):
#   Proxmox -> OPNsense (default gw) -> MWAN internal link -> WAN
# This is the same path clients on vlan0100/vlan0200 use.
#
# Protocol tracking: IPv4 and IPv6 are tested independently.
#   - Both pass:     healthy
#   - One fails:     partial degradation, alert (rate-limited), no rollback
#   - Both fail:     total loss, start rollback timeout
#
# Dependency graph:
#   Deployed by: deploy-mwan.yml (delegate_to: vault)
#   Managed by:  mwan-watchdog.service (Type=simple, Restart=always)
#   Env file:    /etc/mwan-watchdog/watchdog.env

set -euo pipefail

# Source environment (provided by systemd EnvironmentFile or standalone)
if [[ -r /etc/mwan-watchdog/watchdog.env ]]; then
    # shellcheck disable=SC1091
    source /etc/mwan-watchdog/watchdog.env
fi

readonly MWAN_VMID="${MWAN_VMID:-113}"
readonly DEPLOY_WINDOW_MINUTES="${DEPLOY_WINDOW_MINUTES:-30}"
readonly CONNECTIVITY_TIMEOUT_SECONDS="${CONNECTIVITY_TIMEOUT_SECONDS:-60}"
readonly CHECK_INTERVAL_HEALTHY="${CHECK_INTERVAL_HEALTHY:-30}"
readonly CHECK_INTERVAL_DEGRADED="${CHECK_INTERVAL_DEGRADED:-10}"
readonly POST_ROLLBACK_GRACE_SECONDS="${POST_ROLLBACK_GRACE_SECONDS:-120}"
readonly LOG_FILE="${LOG_FILE:-/var/log/mwan-watchdog.log}"
readonly ROLLBACK_STATE_FILE="${ROLLBACK_STATE_FILE:-/run/mwan-rollback.state}"
readonly ROLLBACK_LOCK_FILE="${ROLLBACK_LOCK_FILE:-/run/mwan-watchdog-rollback.lock}"
readonly ALERT_EMAIL="${ALERT_EMAIL:-root@localhost}"
readonly ALERT_COOLDOWN_SECONDS="${ALERT_COOLDOWN_SECONDS:-300}"

# ---------------------------------------------------------------------------
# Signal handling: prevent SIGTERM from leaving the VM stopped mid-rollback
# ---------------------------------------------------------------------------
ROLLING_BACK=false
SHUTDOWN_REQUESTED=false

handle_signal() {
    if [[ "$ROLLING_BACK" == "true" ]]; then
        log "Signal received during rollback; deferring until rollback completes"
        SHUTDOWN_REQUESTED=true
        return
    fi
    log "Signal received; shutting down"
    exit 0
}

trap handle_signal SIGTERM SIGINT

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [mwan-watchdog] $*" | tee -a "$LOG_FILE"
}

error() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [mwan-watchdog] ERROR: $*" >&2
    echo "$(date '+%Y-%m-%d %H:%M:%S') [mwan-watchdog] ERROR: $*" >> "$LOG_FILE"
}

# ---------------------------------------------------------------------------
# VM helpers
# ---------------------------------------------------------------------------
vm_is_running() {
    local status_line
    status_line="$(qm status "$MWAN_VMID" 2>/dev/null || echo "")"
    if [[ "$status_line" == *"running"* ]]; then
        return 0
    fi
    return 1
}

# Run a command inside the VM via the QEMU guest agent (virtio-serial, no
# network needed). Returns the guest exit code, or 1 on any failure.
guest_exec_exitcode() {
    local result
    result="$(qm guest exec "$MWAN_VMID" -- "$@" 2>/dev/null || echo '{"exitcode":1}')"
    jq -r '.exitcode // 1' <<< "$result" 2>/dev/null || echo 1
}

# ---------------------------------------------------------------------------
# Interrupted rollback recovery
# ---------------------------------------------------------------------------
# If the watchdog was killed between qm stop and qm start, the VM could be
# left stopped. The lock file records this in-progress state so a fresh
# instance can finish the job.
recover_interrupted_rollback() {
    if [[ ! -f "$ROLLBACK_LOCK_FILE" ]]; then
        return 0
    fi

    log "Found rollback lock from previous instance"

    if vm_is_running; then
        log "VM is running; previous rollback completed. Removing lock."
        rm -f "$ROLLBACK_LOCK_FILE"
        return 0
    fi

    log "VM is stopped and rollback lock exists; previous rollback was interrupted"
    log "Attempting to start VM $MWAN_VMID to complete recovery"
    if qm start "$MWAN_VMID"; then
        log "VM started successfully after interrupted rollback"
    else
        error "Failed to start VM after interrupted rollback; manual intervention needed"
    fi

    rm -f "$ROLLBACK_LOCK_FILE"

    log "Waiting ${POST_ROLLBACK_GRACE_SECONDS}s for VM to boot and routes to converge"
    sleep "$POST_ROLLBACK_GRACE_SECONDS"
}

# ---------------------------------------------------------------------------
# Deploy window detection
# ---------------------------------------------------------------------------
DEPLOY_TS=""

check_recent_deploy() {
    if ! vm_is_running; then
        return 1
    fi

    local result deploy_ts
    result="$(qm guest exec "$MWAN_VMID" -- cat /var/run/mwan-last-deploy 2>/dev/null || echo '{"exitcode":1}')"
    deploy_ts="$(jq -r '."out-data" // empty' <<< "$result" 2>/dev/null | tr -d '[:space:]' || echo "")"

    if [[ -z "$deploy_ts" ]]; then
        return 1
    fi
    if [[ "$deploy_ts" == "null" ]]; then
        return 1
    fi
    if ! [[ "$deploy_ts" =~ ^[0-9]+$ ]]; then
        return 1
    fi

    local now age_minutes
    now="$(date +%s)"
    age_minutes="$(( (now - deploy_ts) / 60 ))"

    if [[ "$age_minutes" -gt "$DEPLOY_WINDOW_MINUTES" ]]; then
        return 1
    fi

    DEPLOY_TS="$deploy_ts"
    return 0
}

# ---------------------------------------------------------------------------
# Connectivity probes
# ---------------------------------------------------------------------------

# Test IPv4 and IPv6 independently from Proxmox. Sets IPV4_OK and IPV6_OK.
# These route through OPNsense -> MWAN, which is the same path all VLAN
# clients use.
IPV4_OK=false
IPV6_OK=false

probe_main_connectivity() {
    IPV4_OK=false
    IPV6_OK=false

    if ping6 -c 2 -W 3 2606:4700:4700::1111 >/dev/null 2>&1; then
        IPV6_OK=true
    fi
    if ping -c 2 -W 3 1.1.1.1 >/dev/null 2>&1; then
        IPV4_OK=true
    fi
}

# General connectivity from inside the VM (default route, no interface
# binding). If this passes but Proxmox can't reach the internet, the issue
# is between Proxmox and OPNsense/MWAN, not inside MWAN itself.
test_vm_general_connectivity() {
    if ! vm_is_running; then
        return 1
    fi

    local rc
    rc="$(guest_exec_exitcode ping6 -c 2 -W 3 2606:4700:4700::1111)"
    if [[ "$rc" == "0" ]]; then
        return 0
    fi

    rc="$(guest_exec_exitcode ping -c 2 -W 3 1.1.1.1)"
    if [[ "$rc" == "0" ]]; then
        return 0
    fi

    return 1
}

# Probe ISP reachability from inside the VM, binding to each WAN interface.
# Tests whether the raw ISP link is up, regardless of MWAN routing decisions.
test_isp_from_vm() {
    if ! vm_is_running; then
        return 1
    fi

    local rc
    local wan_ifaces=("enwebpass0" "enmbrains0")

    for iface in "${wan_ifaces[@]}"; do
        rc="$(guest_exec_exitcode ping -c 3 -W 3 -I "$iface" 1.1.1.1)"
        if [[ "$rc" == "0" ]]; then
            log "ISP reachable from VM via $iface (IPv4)"
            return 0
        fi

        rc="$(guest_exec_exitcode ping6 -c 3 -W 3 -I "$iface" 2606:4700:4700::1111)"
        if [[ "$rc" == "0" ]]; then
            log "ISP reachable from VM via $iface (IPv6)"
            return 0
        fi
    done

    log "ISP unreachable from VM on all tested WAN interfaces"
    return 1
}

# ---------------------------------------------------------------------------
# Snapshot helpers
# ---------------------------------------------------------------------------
find_rollback_snapshot() {
    qm listsnapshot "$MWAN_VMID" 2>/dev/null \
        | grep -o 'pre-deploy-[^[:space:]]*' \
        | tail -1 \
        || echo ""
}

check_rollback_already_done() {
    local deploy_ts="$1"

    if [[ ! -f "$ROLLBACK_STATE_FILE" ]]; then
        return 1
    fi

    local state_deploy_ts rollback_done
    state_deploy_ts="$(grep '^deploy_timestamp=' "$ROLLBACK_STATE_FILE" | cut -d'=' -f2 || echo "")"
    rollback_done="$(grep '^rollback_done=' "$ROLLBACK_STATE_FILE" | cut -d'=' -f2 || echo "false")"

    if [[ "$state_deploy_ts" != "$deploy_ts" ]]; then
        return 1
    fi
    if [[ "$rollback_done" == "true" ]]; then
        log "Rollback already performed for deploy_ts=$deploy_ts"
        return 0
    fi
    return 1
}

# ---------------------------------------------------------------------------
# Rollback
# ---------------------------------------------------------------------------
perform_rollback() {
    local deploy_ts="$1"
    local snapshot_name="$2"

    ROLLING_BACK=true

    # Write lock BEFORE stopping VM so a restart can detect an interrupted
    # rollback and finish it.
    echo "deploy_ts=$deploy_ts snapshot=$snapshot_name ts=$(date +%s)" \
        > "$ROLLBACK_LOCK_FILE"

    log "INITIATING ROLLBACK to snapshot=$snapshot_name (deploy_ts=$deploy_ts)"

    log "Stopping MWAN VM $MWAN_VMID..."
    qm stop "$MWAN_VMID" --timeout 30 || true

    log "Rolling back to snapshot $snapshot_name..."
    if ! qm rollback "$MWAN_VMID" "$snapshot_name"; then
        error "qm rollback failed; attempting to start VM anyway"
    fi

    log "Starting MWAN VM $MWAN_VMID..."
    if ! qm start "$MWAN_VMID"; then
        error "qm start failed after rollback; VM may be stopped"
    fi

    # Lock is no longer needed; VM should be starting.
    rm -f "$ROLLBACK_LOCK_FILE"

    log "Sending rollback notification..."
    /usr/local/bin/send-email-http.sh \
        -t "$ALERT_EMAIL" \
        -s "MWAN Auto-Rollback Triggered" \
        -m "Rolled back VM $MWAN_VMID to snapshot $snapshot_name at $(date).
Reason: deploy broke connectivity.
Deploy timestamp: $deploy_ts" \
        -k "${SMTP2GO_API_KEY:-}" || error "Failed to send rollback email"

    cat > "$ROLLBACK_STATE_FILE" <<EOF
deploy_timestamp=$deploy_ts
rollback_done=true
rollback_timestamp=$(date +%s)
snapshot=$snapshot_name
EOF

    log "ROLLBACK COMPLETE"

    ROLLING_BACK=false

    if [[ "$SHUTDOWN_REQUESTED" == "true" ]]; then
        log "Deferred shutdown now executing"
        exit 0
    fi
}

# ---------------------------------------------------------------------------
# Alerts (rate-limited)
# ---------------------------------------------------------------------------
NEXT_PARTIAL_ALERT_AT=0
NEXT_TOTAL_ALERT_AT=0

send_partial_alert() {
    local protocol="$1"
    local now
    now="$(date +%s)"

    if [[ "$now" -lt "$NEXT_PARTIAL_ALERT_AT" ]]; then
        return 0
    fi

    log "Sending partial-degradation alert ($protocol down)..."
    /usr/local/bin/send-email-http.sh \
        -t "$ALERT_EMAIL" \
        -s "MWAN: $protocol connectivity lost" \
        -m "$protocol connectivity failed from Proxmox at $(date).
The other protocol is still working, so this is a partial degradation.
Path tested: Proxmox -> OPNsense -> MWAN -> WAN.
Manual investigation may be needed." \
        -k "${SMTP2GO_API_KEY:-}" || error "Failed to send partial alert"

    NEXT_PARTIAL_ALERT_AT=$((now + ALERT_COOLDOWN_SECONDS))
}

send_total_alert() {
    local reason="$1"
    local now
    now="$(date +%s)"

    if [[ "$now" -lt "$NEXT_TOTAL_ALERT_AT" ]]; then
        return 0
    fi

    log "Sending total-loss alert..."
    /usr/local/bin/send-email-http.sh \
        -t "$ALERT_EMAIL" \
        -s "MWAN Connectivity Alert" \
        -m "MWAN connectivity issue at $(date).
Reason: $reason
No recent deploy within ${DEPLOY_WINDOW_MINUTES}m window; manual intervention may be needed." \
        -k "${SMTP2GO_API_KEY:-}" || error "Failed to send total alert"

    NEXT_TOTAL_ALERT_AT=$((now + ALERT_COOLDOWN_SECONDS))
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
main() {
    log "Starting MWAN watchdog (vmid=$MWAN_VMID, deploy_window=${DEPLOY_WINDOW_MINUTES}m, timeout=${CONNECTIVITY_TIMEOUT_SECONDS}s)"

    recover_interrupted_rollback

    local consecutive_total_failures=0
    local total_down_start=0
    local last_state="unknown"
    local vm_stopped_logged=false

    while true; do
        # -------------------------------------------------------------------
        # Step 0: Check if VM is running
        # -------------------------------------------------------------------
        if ! vm_is_running; then
            if [[ "$vm_stopped_logged" == "false" ]]; then
                log "VM $MWAN_VMID is not running"
                vm_stopped_logged=true
            fi
            sleep "$CHECK_INTERVAL_DEGRADED"
            continue
        fi
        vm_stopped_logged=false

        # -------------------------------------------------------------------
        # Step 1: Probe IPv4 and IPv6 independently from Proxmox
        # -------------------------------------------------------------------
        probe_main_connectivity

        if [[ "$IPV4_OK" == "true" && "$IPV6_OK" == "true" ]]; then
            # Both protocols healthy
            if [[ "$last_state" != "healthy" ]]; then
                log "Connectivity OK: IPv4 and IPv6 (was $last_state)"
            fi
            consecutive_total_failures=0
            total_down_start=0
            last_state="healthy"
            NEXT_PARTIAL_ALERT_AT=0
            NEXT_TOTAL_ALERT_AT=0
            sleep "$CHECK_INTERVAL_HEALTHY"
            continue
        fi

        if [[ "$IPV4_OK" == "true" || "$IPV6_OK" == "true" ]]; then
            # Partial degradation: one protocol works, the other does not.
            # Alert but do NOT start the rollback timeout.
            local down_proto="IPv6"
            if [[ "$IPV6_OK" == "true" ]]; then
                down_proto="IPv4"
            fi

            if [[ "$last_state" != "partial" ]]; then
                log "Partial degradation: $down_proto down, other protocol OK"
            fi
            last_state="partial"

            consecutive_total_failures=0
            total_down_start=0
            send_partial_alert "$down_proto"
            sleep "$CHECK_INTERVAL_DEGRADED"
            continue
        fi

        # -------------------------------------------------------------------
        # Step 2: Total connectivity loss (both IPv4 and IPv6 failed)
        # -------------------------------------------------------------------
        consecutive_total_failures=$((consecutive_total_failures + 1))

        if [[ "$total_down_start" -eq 0 ]]; then
            total_down_start="$(date +%s)"
            log "Total connectivity loss (IPv4 and IPv6); starting ${CONNECTIVITY_TIMEOUT_SECONDS}s timeout"
        fi

        local now
        now="$(date +%s)"
        local down_duration=$((now - total_down_start))

        if [[ "$down_duration" -lt "$CONNECTIVITY_TIMEOUT_SECONDS" ]]; then
            last_state="down"
            sleep "$CHECK_INTERVAL_DEGRADED"
            continue
        fi

        last_state="down"

        # -------------------------------------------------------------------
        # Step 3: Timeout exceeded. Distinguish real outage from MWAN failure.
        # -------------------------------------------------------------------

        # First, check if the VM itself can reach the internet via its
        # default route. If yes, MWAN routing is fine and the problem is
        # between Proxmox and OPNsense (or on Proxmox itself). Do not
        # rollback in that case.
        if test_vm_general_connectivity; then
            log "VM has internet via default route; issue is Proxmox-side, not MWAN"
            send_total_alert "Proxmox cannot reach internet but MWAN VM can; Proxmox routing issue"
            sleep 60
            continue
        fi

        # VM also cannot reach the internet. Check if the raw ISP links are
        # up by testing per-interface from inside the VM.
        if ! test_isp_from_vm; then
            if [[ "$consecutive_total_failures" -le 2 ]]; then
                log "ISP also unreachable from VM; likely a real outage (not rolling back)"
            fi
            sleep 60
            continue
        fi

        # ISP is up (at least one WAN interface can reach the internet) but
        # neither Proxmox nor the VM's default route works. This suggests
        # MWAN routing/nftables/NPT is broken.
        log "ISP reachable per-interface but default route broken; MWAN routing failure"

        # -------------------------------------------------------------------
        # Step 4: Decide whether to rollback or alert
        # -------------------------------------------------------------------

        # Re-check deploy window on every iteration so the watchdog picks up
        # new deploys even if it has been running for a long time.
        local rollback_enabled=false
        if check_recent_deploy; then
            rollback_enabled=true
        fi

        if [[ "$rollback_enabled" == "true" ]]; then
            if check_rollback_already_done "$DEPLOY_TS"; then
                sleep 60
                continue
            fi

            local snapshot_name
            snapshot_name="$(find_rollback_snapshot)"
            if [[ -z "$snapshot_name" ]]; then
                log "No pre-deploy snapshot found; cannot rollback"
                send_total_alert "MWAN routing broken after deploy but no pre-deploy snapshot exists"
                sleep 60
                continue
            fi

            perform_rollback "$DEPLOY_TS" "$snapshot_name"

            log "Waiting ${POST_ROLLBACK_GRACE_SECONDS}s for VM to boot and routes to converge"
            sleep "$POST_ROLLBACK_GRACE_SECONDS"
        else
            send_total_alert "MWAN routing broken (no recent deploy; manual intervention needed)"
            sleep 60
        fi
    done
}

main "$@"
