# Use local time instead of UTC
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$template TraditionalFormatWithLocalTime, >-
  "%timegenerated% %HOSTNAME% %syslogtag%%msg:::drop-last-lf%\n"
$ActionFileDefaultTemplate TraditionalFormatWithLocalTime
