#!/usr/bin/env bash
# networkd-dispatcher hook to update NPT after WAN becomes routable
# Generated by Ansible
#
# What it does (symptoms):
# - Ensures IPv6 starts working as soon as a WAN has a delegated prefix (PD) and becomes routable.
# - Prevents “NPT rules missing” failures after DHCP/PD changes.
#
# What it does (technical):
# - Runs only on `STATE=routable` for WAN interfaces.
# - Discovers delegated prefix info and persists it to `/var/lib/mwan/pd-<iface>`.
# - Calls `/usr/local/bin/update-npt.sh <iface> <prefix>` to program runtime `nft ip6 nat` rules.
#
# Dependency graph:
# - Called by: `networkd-dispatcher` on systemd-networkd state transitions.
# - Calls into: `update-npt.sh`.

IFACE="$1"
STATE="$2"

# shellcheck disable=SC1091
. /etc/mwan/mwan.env

# Only act when interface is routable
[ "$STATE" = "routable" ] || exit 0

ATT_IFACE="${MWAN_ATT_VLAN_IFACE:-}"
WEBPASS_IFACE="${MWAN_WEBPASS_IFACE:-}"
MB_IFACE="${MWAN_MONKEYBRAINS_IFACE:-}"

# Only handle WAN interfaces (AT&T VLAN, Webpass, Monkeybrains)
if [ "$IFACE" != "$ATT_IFACE" ] && [ "$IFACE" != "$WEBPASS_IFACE" ] && [ "$IFACE" != "$MB_IFACE" ]; then
    exit 0
fi

log() {
    local prefix=""
    [ -n "${MWAN_TRACE_ID:-}" ] && prefix="traceId=${MWAN_TRACE_ID} "
    logger -t networkd-dispatcher "${prefix}[update-npt] $*"
    echo "[update-npt] ${prefix}$*"
}

# Session-style debug logging (JSON lines)
DEBUG="${MWAN_DEBUG_LOGGING:-0}"
DEBUG_LOG="${MWAN_DEBUG_LOG:-/var/log/mwan-debug.log}"
TRACE_FILE="${MWAN_TRACE_FILE:-/run/mwan-trace-id}"
MWAN_TRACE_ID="${MWAN_TRACE_ID:-}"
if [ -z "${MWAN_TRACE_ID:-}" ] && [ -r "$TRACE_FILE" ]; then
    MWAN_TRACE_ID="$(cat "$TRACE_FILE")"
fi
debug_json_line() {
    [ "$DEBUG" = "1" ] || return 0
    local loc="$1"; shift
    local msg="$1"; shift
    local data="${1:-{}}"; shift || true
    jq -cn \
        --arg traceId "${MWAN_TRACE_ID:-}" \
        --arg component "55-update-npt" \
        --arg location "$loc" \
        --arg message "$msg" \
        --arg data "$data" \
        --argjson timestamp "$(date +%s%3N)" \
        '{
          traceId:$traceId,
          component:$component,
          location:$location,
          message:$message,
          data:(try ($data|fromjson) catch {"_raw":$data}),
          timestamp:$timestamp
        }' \
        >>"$DEBUG_LOG"
}

#region agent log
LOG_PATH="/var/log/mwan-debug.log"
log_json() {
    local hid="$1"; shift
    local loc="$1"; shift
    local msg="$1"; shift
    local data="$1"; shift
    jq -cn \
        --arg traceId "${MWAN_TRACE_ID:-}" \
        --arg sessionId "debug-session" \
        --arg runId "run1" \
        --arg hypothesisId "$hid" \
        --arg location "$loc" \
        --arg message "$msg" \
        --arg data "$data" \
        --argjson timestamp "$(date +%s%3N)" \
        '{
          traceId:$traceId,
          sessionId:$sessionId,
          runId:$runId,
          hypothesisId:$hypothesisId,
          location:$location,
          message:$message,
          data:(try ($data|fromjson) catch {"_raw":$data}),
          timestamp:$timestamp
        }' \
        >>"$LOG_PATH"
}
#endregion

log "Event iface=$IFACE state=$STATE"
EVENT_DATA="$(jq -cn \
    --arg iface "$IFACE" \
    --arg state "$STATE" \
    '{
      iface: $iface,
      state: $state
    }')"
log_json "H1" "55-update-npt.sh:EVENT" "hook_event" "$EVENT_DATA"
debug_json_line "EVENT" "hook_event" "$EVENT_DATA"

# Capture DHCPv6-PD routes (systemd installs PD routes as proto dhcp, dev lo)
ROUTE_JSON="$(ip -j -6 route show proto dhcp 2>/dev/null || echo '[]')"
ROUTE_OUTPUT="$(ip -6 route show proto dhcp || true)"
log "DHCPv6 proto dhcp routes:\n$ROUTE_OUTPUT"
ROUTE_DATA="$(jq -cn \
    --argjson routes "$ROUTE_JSON" \
    '{
      routes: $routes
    }')"
log_json "H1" "55-update-npt.sh:ROUTES" "dhcp_routes" \
    "$ROUTE_DATA"
debug_json_line "ROUTES" "dhcp_routes" "$ROUTE_DATA"

# Try to extract prefixes
STATE_DIR="/var/lib/mwan"
mkdir -p "$STATE_DIR"
STATE_FILE="$STATE_DIR/pd-$IFACE"

# Discover PD prefixes via a single canonical helper (Describe/networkctl/routes/journal/statefile).
PREFIXES="$(/usr/local/bin/find-pd-prefixes.sh "$IFACE" | tr '\n' ' ' | xargs)"

# IMPORTANT:
# `ip -6 route show proto dhcp` is not reliably per-interface (often shows PD routes without an iface
# association, e.g. dev lo). Using it here can accidentally attribute Webpass PD to AT&T (or vice versa).
# For AT&T + Webpass, prefer the configured static /60 targets; for Monkeybrains, allow dynamic discovery.
case "$IFACE" in
    "$ATT_IFACE") PREFIXES="${MWAN_NPT_ATT_PREFIX:-}" ;;
    "$WEBPASS_IFACE") PREFIXES="${MWAN_NPT_WEBPASS_PREFIX:-}" ;;
    *)
        # 2) proto dhcp routes (coarse; may include prefixes from other ifaces)
        if [ -z "$PREFIXES" ]; then
            PREFIXES="$(jq -r '.[].dst // empty' <<<"$ROUTE_JSON" | tr '\n' ' ' | xargs)"
        fi
        ;;
esac

# Monkeybrains: optionally hardcode a /60 target to avoid unreliable discovery.
if [ "$IFACE" = "$MB_IFACE" ] && [ -n "${MWAN_NPT_MONKEYBRAINS_PREFIX:-}" ]; then
    PREFIXES="${MWAN_NPT_MONKEYBRAINS_PREFIX}"
fi

# 3) state file fallback
if [ -z "$PREFIXES" ] && [ -f "$STATE_FILE" ]; then
    PREFIXES=$(cat "$STATE_FILE")
fi

PREFIX_DATA="$(jq -cn \
    --arg prefixes "$PREFIXES" \
    '{
      prefixes: $prefixes
    }')"
log_json "H2" "55-update-npt.sh:PREFIXES" "prefixes_found" "$PREFIX_DATA"
debug_json_line "PREFIXES" "prefixes_found" "$PREFIX_DATA"

if [ -z "$PREFIXES" ]; then
    # Fallback mode:
    # Some deployments intentionally use fixed per-WAN /60 targets (NPT) rather than
    # relying on dynamically-discovered DHCPv6-PD routes.
    case "$IFACE" in
        "$ATT_IFACE") PREFIXES="${MWAN_NPT_ATT_PREFIX:-}" ;;
        "$WEBPASS_IFACE") PREFIXES="${MWAN_NPT_WEBPASS_PREFIX:-}" ;;
        "$MB_IFACE") PREFIXES="${MWAN_NPT_MONKEYBRAINS_PREFIX:-}" ;;
        *) PREFIXES="" ;;
    esac
    if [ -n "$PREFIXES" ]; then
        FALLBACK_DATA="$(jq -cn \
            --arg iface "$IFACE" \
            --arg prefixes "$PREFIXES" \
            '{
              iface: $iface,
              prefixes: $prefixes
            }')"
        debug_json_line "FALLBACK" "using_static_prefix" "$FALLBACK_DATA"
    fi
fi

if [ -z "$PREFIXES" ]; then
    log "No prefix found for $IFACE; skipping NPT update"
    exit 0
fi

# Persist latest prefixes
echo "$PREFIXES" > "$STATE_FILE"

log "Found prefixes: $PREFIXES"
FOUND_DATA="$(jq -cn \
    --arg prefixes "$PREFIXES" \
    '{
      prefixes: $prefixes
    }')"
log_json "H3" "55-update-npt.sh:FOUND" "prefixes_nonempty" "$FOUND_DATA"
debug_json_line "FOUND" "prefixes_nonempty" "$FOUND_DATA"

for prefix in $PREFIXES; do
    log "Updating NPT for $IFACE with prefix $prefix"
    CALL_DATA="$(jq -cn \
        --arg iface "$IFACE" \
        --arg prefix "$prefix" \
        '{
          iface: $iface,
          prefix: $prefix
        }')"
    log_json "H4" "55-update-npt.sh:CALL" "calling_update_npt" "$CALL_DATA"
    debug_json_line "CALL" "calling_update_npt" "$CALL_DATA"
    /usr/local/bin/update-npt.sh "$IFACE" "$prefix" || \
        log "NPT update failed for $IFACE prefix $prefix"
done
