frr defaults datacenter
hostname mwan-testbed
log syslog informational
!
router bgp 4200000001
 bgp router-id 10.250.250.3
 no bgp default ipv4-unicast
 neighbor 10.250.250.2 remote-as 4200000001
 neighbor 10.250.250.2 bfd
 neighbor 3d06:bad:b01:201::2 remote-as 4200000001
 neighbor 3d06:bad:b01:201::2 bfd
 !
 address-family ipv4 unicast
  neighbor 10.250.250.2 activate
  network 0.0.0.0/0
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 3d06:bad:b01:201::2 activate
  network ::/0
 exit-address-family
exit
!
bfd
 peer 10.250.250.2
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 exit
 !
 peer 3d06:bad:b01:201::2
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 exit
exit
