---
- name: Stop and disable suburban DDNS timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - 'cloudflare-dynamic-dns@128\x2dnj.timer'
    - 'cloudflare-dynamic-dns@128\x2dnj6.timer'
    - cloudflare-dynamic-dns@128-nj.timer
    - cloudflare-dynamic-dns@128-nj6.timer

- name: Stop and disable suburban ddclient
  ansible.builtin.systemd:
    name: ddclient.service
    enabled: false
    state: stopped

- name: Remove suburban DDNS configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/cloudflare-dynamic-dns/config.d/128-nj.yaml
    - /etc/cloudflare-dynamic-dns/config.d/128-nj6.yaml
    - /etc/systemd/system/cloudflare-dynamic-dns@.timer
    - /etc/ddclient.conf

- name: Remove suburban DDNS packages
  ansible.builtin.apt:
    name:
      - cloudflare-dynamic-dns
      - ddclient
    state: absent

- name: Reload systemd after DDNS removal
  ansible.builtin.systemd:
    daemon_reload: true
