#!/bin/sh
# PROVIDE: mwan_opnsense
# REQUIRE: NETWORKING FILESYSTEMS
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable mwan-opnsense:
#   mwan_opnsense_enable="YES"
#
# Optional settings (set in /etc/rc.conf.d/mwan_opnsense):
#   mwan_opnsense_listen_serial="/dev/ttyV0.1"
#   mwan_opnsense_logfile="/var/log/mwan-opnsense.log"

. /etc/rc.subr

name="mwan_opnsense"
rcvar="${name}_enable"

load_rc_config $name

: ${mwan_opnsense_enable:="NO"}
: ${mwan_opnsense_listen_serial:="/dev/ttyV0.1"}
: ${mwan_opnsense_logfile:="/var/log/mwan-opnsense.log"}

pidfile="/var/run/${name}.pid"
procname="/usr/local/sbin/mwan-opnsense"
command="/usr/sbin/daemon"
command_args="-r -P ${pidfile} -o ${mwan_opnsense_logfile} ${procname} serve \
    -serial \"${mwan_opnsense_listen_serial}\""

run_rc_command "$1"
